version: "3.1"
services:
  monappjava :
    image: tpdocker
    depends_on:
      - postgres
    ports:
      - "8090:8090" #port de mon appli spring
    networks:
      - monreseau
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres #obligation de mettre un mdp pour postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  postgres:
    image: 'postgres:bullseye' #image provenant de docker hub en version bullseye
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - monreseau
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      #PGDATA: /var/lib/postgresql/data/pgdata
volumes:
  data:
networks:
  monreseau: #permet de mettre en reseau Spring et postgres
